
CREATE PROCEDURE LIST_APPLICATION_INSTANCE
AS
BEGIN
	SELECT APP.APPLICATION_ID,
		   APP.APPLICATION_NAME,
		   INST.INSTANCE_ID,
		   INST.INSTANCE_NAME
	FROM TB_APPLICATION APP
	INNER JOIN TB_INSTANCE INST ON APP.APPLICATION_ID = INST.APPLICATION_ID 
	WHERE INST.ST_ENABLE = 1
END
