USE DB_CONFIGURATION_MANAGER
GO

IF (OBJECT_ID('TB_INSTANCE_LABRARY_REFERENCE') IS NOT NULL)
BEGIN
	DROP TABLE TB_INSTANCE_LABRARY_REFERENCE
END
GO

IF (OBJECT_ID('TB_LIBRARY_PROPERTY') IS NOT NULL)
BEGIN
	DROP TABLE TB_LIBRARY_PROPERTY
END
GO

IF (OBJECT_ID('TB_LIBRARY') IS NOT NULL)
BEGIN
	DROP TABLE TB_LIBRARY
END
GO

IF (OBJECT_ID('TB_INSTANCE_INTEGRATION') IS NOT NULL)
BEGIN
	DROP TABLE TB_INSTANCE_INTEGRATION
END
GO

IF (OBJECT_ID('TB_INSTANCE_PROPERTY') IS NOT NULL)
BEGIN
	DROP TABLE TB_INSTANCE_PROPERTY
END
GO

IF (OBJECT_ID('TB_PROPERTY') IS NOT NULL)
BEGIN
	DROP TABLE TB_PROPERTY
END
GO

IF (OBJECT_ID('TB_INSTANCE') IS NOT NULL)
BEGIN
	DROP TABLE TB_INSTANCE
END
GO

IF (OBJECT_ID('TB_APPLICATION') IS NOT NULL)
BEGIN
	DROP TABLE TB_APPLICATION
END
GO

CREATE TABLE TB_APPLICATION (
	APPLICATION_ID	INT IDENTITY(1,1)				CONSTRAINT PK_APPLICATION PRIMARY KEY,
	APPLICATION_NAME VARCHAR(50)		NOT NULL	CONSTRAINT UN_APPLICATION_NAME UNIQUE,
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_APPLICATION_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_APPLICATION_ENABLE DEFAULT 1
)
GO

CREATE TABLE TB_PROPERTY (
	PROPERTY_ID			INT IDENTITY(1,1)				CONSTRAINT PK_PROPERTY PRIMARY KEY,
	PROPERTY_NAME		VARCHAR(20)			NOT NULL, 
	PROPERTY_TYPE		VARCHAR(15)			NOT NULL, 
	SETTING_REFERENCE	VARCHAR(20)			NULL, 
	APPLICATION_ID		INT					NOT NULL	CONSTRAINT FK_PROPERTY_PROPERTY FOREIGN KEY REFERENCES TB_APPLICATION(APPLICATION_ID),
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_PROPERTY_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_PROPERTY_ENABLE DEFAULT 1
)
GO

CREATE TABLE TB_INSTANCE (
	INSTANCE_ID		INT IDENTITY(1,1)				CONSTRAINT PK_INSTANCE PRIMARY KEY,
	INSTANCE_NAME	VARCHAR(50)			NOT NULL	CONSTRAINT UN_INSTANCE_NAME UNIQUE, 
	APPLICATION_ID  INT					NOT NULL	CONSTRAINT FK_APPLICATION_INSTANCE FOREIGN KEY REFERENCES TB_APPLICATION(APPLICATION_ID),
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_INSTANCE_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_INSTANCE_ENABLE DEFAULT 1
)
GO


CREATE TABLE TB_INSTANCE_PROPERTY (
	INSTANCE_PROPERTY_ID	INT IDENTITY(1,1)				CONSTRAINT PK_INSTANCE_PROPERTY PRIMARY KEY,
	INSTANCE_ID				INT					NOT NULL	CONSTRAINT FK_INSTANCE_PROPERTY_INSTANCE FOREIGN KEY REFERENCES TB_INSTANCE(INSTANCE_ID),
	PROPERTY_ID				INT					NOT NULL	CONSTRAINT FK_INSTANCE_PROPERTY_PROPERTY FOREIGN KEY REFERENCES TB_PROPERTY(PROPERTY_ID),
	PROPERTY_VALUE			VARCHAR(200)		NOT NULL,
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_INSTANCE_PROPERTY_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_INSTANCE_PROPERTY_ENABLE DEFAULT 1
)
GO

CREATE TABLE TB_INSTANCE_INTEGRATION (
	INSTANCE_PROPERTY_ID	INT IDENTITY(1,1)				CONSTRAINT PK_INSTANCE_INTEGRATION PRIMARY KEY,
	CLIENT_INSTANCE_ID		INT					NOT NULL	CONSTRAINT FK_CLIENT_INSTANCE_INTEGRATION_INSTANCE FOREIGN KEY REFERENCES TB_INSTANCE(INSTANCE_ID),
	CLIENT_PROPERTY_ID		INT					NOT NULL	CONSTRAINT FK_CLIENT_INSTANCE_INTEGRATION_PROPERTY FOREIGN KEY REFERENCES TB_PROPERTY(PROPERTY_ID),
	SERVER_INSTANCE_ID		INT					NOT NULL	CONSTRAINT FK_SERVER_INSTANCE_INTEGRATION_INSTANCE FOREIGN KEY REFERENCES TB_INSTANCE(INSTANCE_ID),
	SERVER_PROPERTY_ID		INT					NOT NULL	CONSTRAINT FK_SERVER_INSTANCE_INTEGRATION_PROPERTY FOREIGN KEY REFERENCES TB_PROPERTY(PROPERTY_ID),
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_INSTANCE_INTEGRATION_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_INSTANCE_INTEGRATION_ENABLE DEFAULT 1
)
GO


CREATE TABLE TB_LIBRARY (
	LIBRARY_ID	 INT IDENTITY(1,1)				CONSTRAINT PK_LIBRARY PRIMARY KEY,
	LIBRARY_NAME VARCHAR(50)		NOT NULL	CONSTRAINT UN_LIBRARY_NAME UNIQUE,
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_LIBRARY_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_LIBRARY_ENABLE DEFAULT 1
)
GO

CREATE TABLE TB_LIBRARY_PROPERTY (
	LIBRARY_PROPERTY_ID			INT IDENTITY(1,1)				CONSTRAINT PK_LIBRARY_PROPERTY PRIMARY KEY,
	LIBRARY_PROPERTY_NAME		VARCHAR(20)			NOT NULL	CONSTRAINT UN_LIBRARY_PROPERTY_NAME UNIQUE, 
	LIBRARY_PROPERTY_TYPE		VARCHAR(15)			NOT NULL, 
	LIBRARY_ID					INT					NOT NULL	CONSTRAINT FK_LIBRARY_PROPERTY_LIBRARY_PROPERTY FOREIGN KEY REFERENCES TB_LIBRARY(LIBRARY_ID),
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_LIBRARY_PROPERTY_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_LIBRARY_PROPERTY_ENABLE DEFAULT 1
)
GO

CREATE TABLE TB_INSTANCE_LABRARY_REFERENCE (
	INSTANCE_LABRARY_REFERENCE_ID	INT IDENTITY(1,1)				CONSTRAINT PK_INSTANCE_LABRARY_REFERENCE PRIMARY KEY,
	INSTANCE_ID						INT					NOT NULL	CONSTRAINT FK_INSTANCE_LABRARY_REFERENCE_INSTANCE FOREIGN KEY REFERENCES TB_INSTANCE(INSTANCE_ID),
	LIBRARY_PROPERTY_ID				INT					NOT NULL	CONSTRAINT FK_INSTANCE_LABRARY_REFERENCE_LIBRARY_PROPERTY FOREIGN KEY REFERENCES TB_LIBRARY_PROPERTY(LIBRARY_PROPERTY_ID),
	PROPERTY_VALUE					VARCHAR(200)		NOT NULL,
	USER_CREATED VARCHAR(20)		NOT NULL,
	DT_CREATED DATETIME				NOT NULL	CONSTRAINT DT_INSTANCE_LABRARY_REFERENCE_CREATED DEFAULT GETDATE(),
	USER_UPDATED VARCHAR(20)		NULL,
	DT_UPDATED DATETIME				NULL,
	ST_ENABLE BIT					NOT NULL	CONSTRAINT DT_INSTANCE_LABRARY_REFERENCE_ENABLE DEFAULT 1
)
GO