CREATE TABLE [dbo].[TB_APPLICATION] (
    [APPLICATION_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [APPLICATION_NAME] VARCHAR (50) NOT NULL,
    [USER_CREATED]     VARCHAR (40) NOT NULL,
    [DT_CREATED]       DATETIME     CONSTRAINT [DT_APPLICATION_CREATED] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]     VARCHAR (40) NULL,
    [DT_UPDATED]       DATETIME     NULL,
    [ST_ENABLE]        BIT          CONSTRAINT [DT_APPLICATION_ENABLE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_APPLICATION] PRIMARY KEY CLUSTERED ([APPLICATION_ID] ASC),
    CONSTRAINT [UN_APPLICATION_NAME] UNIQUE NONCLUSTERED ([APPLICATION_NAME] ASC)
);

