CREATE TABLE [dbo].[TB_INSTANCE_LABRARY_REFERENCE] (
    [INSTANCE_LABRARY_REFERENCE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [INSTANCE_ID]                   INT           NOT NULL,
    [LIBRARY_PROPERTY_ID]           INT           NOT NULL,
    [PROPERTY_VALUE]                VARCHAR (200) NOT NULL,
    [USER_CREATED]                  VARCHAR (40)  NOT NULL,
    [DT_CREATED]                    DATETIME      CONSTRAINT [DT_INSTANCE_LABRARY_REFERENCE_CREATED] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]                  VARCHAR (40)  NULL,
    [DT_UPDATED]                    DATETIME      NULL,
    [ST_ENABLE]                     BIT           CONSTRAINT [DT_INSTANCE_LABRARY_REFERENCE_ENABLE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_INSTANCE_LABRARY_REFERENCE] PRIMARY KEY CLUSTERED ([INSTANCE_LABRARY_REFERENCE_ID] ASC),
    CONSTRAINT [FK_INSTANCE_LABRARY_REFERENCE_INSTANCE] FOREIGN KEY ([INSTANCE_ID]) REFERENCES [dbo].[TB_INSTANCE] ([INSTANCE_ID]),
    CONSTRAINT [FK_INSTANCE_LABRARY_REFERENCE_LIBRARY_PROPERTY] FOREIGN KEY ([LIBRARY_PROPERTY_ID]) REFERENCES [dbo].[TB_LIBRARY_PROPERTY] ([LIBRARY_PROPERTY_ID])
);

