CREATE TABLE [dbo].[TB_INSTANCE_PROPERTY] (
    [INSTANCE_PROPERTY_ID] INT           IDENTITY (1, 1) NOT NULL,
    [INSTANCE_ID]          INT           NOT NULL,
    [PROPERTY_ID]          INT           NOT NULL,
    [PROPERTY_VALUE]       VARCHAR (200) NOT NULL,
    [USER_CREATED]         VARCHAR (40)  NOT NULL,
    [DT_CREATED]           DATETIME      CONSTRAINT [DT_INSTANCE_PROPERTY_CREATED] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]         VARCHAR (40)  NULL,
    [DT_UPDATED]           DATETIME      NULL,
    [ST_ENABLE]            BIT           CONSTRAINT [DT_INSTANCE_PROPERTY_ENABLE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_INSTANCE_PROPERTY] PRIMARY KEY CLUSTERED ([INSTANCE_PROPERTY_ID] ASC),
    CONSTRAINT [FK_INSTANCE_PROPERTY_INSTANCE] FOREIGN KEY ([INSTANCE_ID]) REFERENCES [dbo].[TB_INSTANCE] ([INSTANCE_ID]),
    CONSTRAINT [FK_INSTANCE_PROPERTY_PROPERTY] FOREIGN KEY ([PROPERTY_ID]) REFERENCES [dbo].[TB_PROPERTY] ([PROPERTY_ID])
);

