CREATE TABLE [dbo].[TB_LIBRARY] (
    [LIBRARY_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [LIBRARY_NAME] VARCHAR (50) NOT NULL,
    [USER_CREATED] VARCHAR (40) NOT NULL,
    [DT_CREATED]   DATETIME     CONSTRAINT [DT_LIBRARY_CREATED] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED] VARCHAR (40) NULL,
    [DT_UPDATED]   DATETIME     NULL,
    [ST_ENABLE]    BIT          CONSTRAINT [DT_LIBRARY_ENABLE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_LIBRARY] PRIMARY KEY CLUSTERED ([LIBRARY_ID] ASC),
    CONSTRAINT [UN_LIBRARY_NAME] UNIQUE NONCLUSTERED ([LIBRARY_NAME] ASC)
);

