CREATE TABLE [dbo].[TB_LIBRARY_PROPERTY] (
    [LIBRARY_PROPERTY_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [LIBRARY_PROPERTY_NAME] VARCHAR (40) NOT NULL,
    [LIBRARY_PROPERTY_TYPE] VARCHAR (15) NOT NULL,
    [LIBRARY_ID]            INT          NOT NULL,
    [USER_CREATED]          VARCHAR (40) NOT NULL,
    [DT_CREATED]            DATETIME     CONSTRAINT [DT_LIBRARY_PROPERTY_CREATED] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]          VARCHAR (40) NULL,
    [DT_UPDATED]            DATETIME     NULL,
    [ST_ENABLE]             BIT          CONSTRAINT [DT_LIBRARY_PROPERTY_ENABLE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_LIBRARY_PROPERTY] PRIMARY KEY CLUSTERED ([LIBRARY_PROPERTY_ID] ASC),
    CONSTRAINT [FK_LIBRARY_PROPERTY_LIBRARY_PROPERTY] FOREIGN KEY ([LIBRARY_ID]) REFERENCES [dbo].[TB_LIBRARY] ([LIBRARY_ID]),
    CONSTRAINT [UN_LIBRARY_PROPERTY_NAME] UNIQUE NONCLUSTERED ([LIBRARY_PROPERTY_NAME] ASC)
);

