CREATE TABLE [dbo].[TB_PROPERTY] (
    [PROPERTY_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [PROPERTY_NAME]     VARCHAR (40)  NOT NULL,
    [PROPERTY_TYPE]     VARCHAR (15)  NOT NULL,
    [SETTING_REFERENCE] VARCHAR (100) NULL,
    [APPLICATION_ID]    INT           NOT NULL,
    [USER_CREATED]      VARCHAR (40)  NOT NULL,
    [DT_CREATED]        DATETIME      CONSTRAINT [DT_PROPERTY_CREATED] DEFAULT (getdate()) NOT NULL,
    [USER_UPDATED]      VARCHAR (40)  NULL,
    [DT_UPDATED]        DATETIME      NULL,
    [ST_ENABLE]         BIT           CONSTRAINT [DT_PROPERTY_ENABLE] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_PROPERTY] PRIMARY KEY CLUSTERED ([PROPERTY_ID] ASC),
    CONSTRAINT [FK_PROPERTY_PROPERTY] FOREIGN KEY ([APPLICATION_ID]) REFERENCES [dbo].[TB_APPLICATION] ([APPLICATION_ID])
);

